POST  http://localhost:3030/api/login HTTP/1.1
Content-Type: : application/json
{
    "email":"1234@1234.com",
    "password": "1234567"
}
###

POST http://localhost:3030/api/resetPassword HTTP/1.1
Content-Type: : application/json
{
    "email":"1234@1234.com"
}
###

POST http://localhost:3030/api/changepassword HTTP/1.1
{
    "firstName": "khamlar",
    "lastName":"aaabbccddd",
    "email":"1234@1234.com",
    "password": "aaaaaaa"
}
###

POST http://localhost:3030/api/forgot-password HTTP/1.1
{
    "firstName": "khamlar",
    "lastName":"aaabbccddd",
    "email":"1234@1234.com",
}

