GET http://localhost:3030/api/product/get-product HTTP/1.1

###
GET http://localhost:3030/api/product/1 HTTP/1.1

###
POST http://localhost:3030/api/product/add-product HTTP/1.1
content-type: application/json
{
    "prodName": "prodName",
    "price":1000,
    "qty":10,
    "dsc": "sdasasd",
    "variand": "asdasd",
}

###
DELETE http://localhost:3030/api/product/2 HTTP/1.1

###

PUT http://localhost:3030/api/product/edit-product HTTP/1.1
Content-Type: : application/json
{
    "id": 3,
    "prodName": "prodName",
    "price":1000,
    "qty":10,
    "dsc": "sdasasd",
    "variand": "asdasd",
}