GET http://localhost:3030/api/user/get-user HTTP/1.1

###
GET http://localhost:3030/api/user/1 HTTP/1.1

###
POST http://localhost:3030/api/user/add-user HTTP/1.1
content-type: application/json
{
    "firstName": "khamlar",
    "lastName":"aaabbccddd",
    "email":"1234@1234.com"
}

###
DELETE http://localhost:3030/api/user/2 HTTP/1.1

PUT http://localhost:3030/api/user/edit-user HTTP/1.1